//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresse
    {
        public int N_Adresse { get; set; }
        public string Adresse1 { get; set; }
        public int N_Quartier { get; set; }
    
        public virtual Quartier Quartier { get; set; }
    }
}
