//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fabrication
    {
        public int N_Fab { get; set; }
        public int N_Pizza { get; set; }
        public int QuantitéFab { get; set; }
        public System.DateTime Date_Fab { get; set; }
    
        public virtual CataloguePizza CataloguePizza { get; set; }
    }
}
