//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class LignesCdeClient
    {
        public int N_LigneCde { get; set; }
        public int N_CdeClient { get; set; }
        public int N_Pizza { get; set; }
        public int Quantité { get; set; }
    
        public virtual CataloguePizza CataloguePizza { get; set; }
        public virtual CdeClient CdeClient { get; set; }
    }
}
