//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paiement_Fact_Client
    {
        public int N_PieceComptable { get; set; }
        public int N_Facture { get; set; }
        public System.DateTime Date_Facture { get; set; }
    
        public virtual Facture_Client_BonLiv Facture_Client_BonLiv { get; set; }
    }
}
